/* 날짜 : 2024/03/04
   이름 : 최이진
   내용 : 1장 데이터베이스 와 DBMS 개요
*/

-- 실습하기
CREATE TABLE TYPE_TEST_NUMBER(
        num1 NUMBER,
        num2 NUMBER(2),
        num3 NUMBER(3,1),
        num4 NUMBER(4,2),
        num5 NUMBER(5,6)
);

// num1 NUMBER
INSERT INTO TYPE_TEST_NUMBER (num1) VALUES (1);
INSERT INTO TYPE_TEST_NUMBER (num1) VALUES (123);
INSERT INTO TYPE_TEST_NUMBER (num1) VALUES (123.74);
INSERT INTO TYPE_TEST_NUMBER (num1) VALUES (123.12345);

// num2 NUMBER(2)
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (12);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (123);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (1.2);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (1.23);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (12.34567);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (12.56789);
INSERT INTO TYPE_TEST_NUMBER (num2) VALUES (123.56789);

// num3 NUMBER(3,1)
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (12);
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (123);
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (12.1);
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (12.1234);
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (12.56789);
INSERT INTO TYPE_TEST_NUMBER (num3) VALUES (123.56789);

CREATE TABLE TYPE_TEST_CHAR (
    char1 CHAR(1),
    char2 CHAR(2),
    char3 CHAR(3),
    vchar1 VARCHAR2(1),
    vchar2 VARCHAR2(2),
    vchar3 VARCHAR2(3),
    nvchar1 NVARCHAR2(1),
    nvchar2 NVARCHAR2(2),
    nvchar3 NVARCHAR2(3)
);
// CHAR
INSERT INTO type_test_char (char1) VALUES ('A');
INSERT INTO type_test_char (char1) VALUES ('가');

// VARCHAR2
INSERT INTO type_test_char (vchar1) VALUES ('A');
INSERT INTO type_test_char (vchar2) VALUES ('AB');
INSERT INTO type_test_char (vchar3) VALUES ('가');

// NVARCHAR2
INSERT INTO type_test_char (nvchar1) VALUES ('A');
INSERT INTO type_test_char (nvchar2) VALUES ('AB');
INSERT INTO type_test_char (nvchar3) VALUES ('가나다');
